### ISSUE TITLE
logout button wrong spot

### ISSUE THREAD

**Issue by maddox05** [maddox05/link-minifier#12]
logout button goes into wrong spot after logging in, goes far left as to where it should replace the login button.

**Comment by AniruddhaGawali** [comment]
i can help in that can you assign ti to me

**Comment by LightAndy1** [comment]
I'm not certain, but I think I've fixed it. I'm waiting for #13 to be accepted so I can test it out.

> _Edit: I've added 'float-right' as being a possible fix._

**Comment by LightAndy1** [comment]
Apparently, this is not fixed. The Logout button is still on the left side:
![image](https://github.com/maddox05/link-minifier/assets/50150516/23e11aaa-8005-4768-a4d0-7697e248ac11)

**Comment by LightAndy1** [comment]
I'll try to fix it as soon as possible. Could you please reopen this issue? @maddox05

**Comment by maddox05** [comment]
yes reopened now

**Comment by LightAndy1** [comment]
@maddox05 the problem has been resolved with PR #15. You can close the issue :)
